### ISSUE TITLE
maven version

### ISSUE THREAD

**Issue by martinbe1io** [OddPrints/pwinty-java-sdk#6]
Hi Pwinty Team, 

i do not find a maven package for your outstanding library. Is it planned to deploy to maven central as well?

thx

Martin

**Comment by mattburns** [comment]
hey @martinbe1io ,
I'm not actually anything to do with Pwinty, I built OddPrints.com and wrote this for our own usage of the Pwinty API.

I'm afraid I've not got any plans to push this to maven central due to the low demand (you're the first other user I'm aware of!). We're also still quite happily using v2.6 of their api which isn't the latest.
